org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=384m -XX:+UseSerialGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=true
org.gradle.workers.max=2
org.gradle.caching=true
kotlin.daemon.jvm.options=-Xmx512m -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC