// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5B57WEPtiPY4QRCwzcKeWmtKo_rSi_s',
    appId: '1:995149800832:web:bccd1bd746edace3b60d65',
    messagingSenderId: '995149800832',
    projectId: 'receipto-ai',
    authDomain: 'receipto-ai.firebaseapp.com',
    storageBucket: 'receipto-ai.firebasestorage.app',
    measurementId: 'G-VP358R03WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG0deqarUjuji-ffcsckA0sp3SQzfgDHM',
    appId: '1:995149800832:android:0b9831b5c54c995bb60d65',
    messagingSenderId: '995149800832',
    projectId: 'receipto-ai',
    storageBucket: 'receipto-ai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD09S-pAP0oB6EH-D2Jim4wF9_w5ZY0OKc',
    appId: '1:995149800832:ios:7f18cf79cae38807b60d65',
    messagingSenderId: '995149800832',
    projectId: 'receipto-ai',
    storageBucket: 'receipto-ai.firebasestorage.app',
    iosClientId: '995149800832-e6q07cp9oh8dc01jel41euhsv8gf72l7.apps.googleusercontent.com',
    iosBundleId: 'com.receipto.receipto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD09S-pAP0oB6EH-D2Jim4wF9_w5ZY0OKc',
    appId: '1:995149800832:ios:7f18cf79cae38807b60d65',
    messagingSenderId: '995149800832',
    projectId: 'receipto-ai',
    storageBucket: 'receipto-ai.firebasestorage.app',
    iosClientId: '995149800832-e6q07cp9oh8dc01jel41euhsv8gf72l7.apps.googleusercontent.com',
    iosBundleId: 'com.receipto.receipto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs5B57WEPtiPY4QRCwzcKeWmtKo_rSi_s',
    appId: '1:995149800832:web:9984b465c2a38312b60d65',
    messagingSenderId: '995149800832',
    projectId: 'receipto-ai',
    authDomain: 'receipto-ai.firebaseapp.com',
    storageBucket: 'receipto-ai.firebasestorage.app',
    measurementId: 'G-FEXZ674VXD',
  );
}
